name: menuapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.5
  dio: ^5.5.0+1
  dartz: ^0.10.1
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  permission_handler: ^11.3.1
  go_router: ^14.2.8
  hive: ^2.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
