// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:menuapp/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MealTimingsAdapter());
    registerAdapter(MealTypeAdapter());
    registerAdapter(MenuResponseModelAdapter());
    registerAdapter(MetaAdapter());
    registerAdapter(SpecialDayAdapter());
    registerAdapter(TimingsAdapter());
  }
}
